<?php

namespace ContainerWENvj7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_07GXJmXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.07GXJmX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.07GXJmX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recette' => ['privates', '.errored.v44IN6B', NULL, 'Cannot determine controller argument for "App\\Controller\\RecetteController::detail()": the $recette argument is type-hinted with the non-existent class or interface: "App\\Entity\\Recette".'],
        ], [
            'recette' => '?',
        ]);
    }
}
