<?php

namespace ContainerWENvj7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_V44IN6BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.v44IN6B' shared service.
     *
     * @return \App\Entity\Recette
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\RecetteController::detail()": the $recette argument is type-hinted with the non-existent class or interface: "App\\Entity\\Recette".');
    }
}
