<?php

namespace ContainerWENvj7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BN8O0J7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bN8O0J7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bN8O0J7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ProductController::salades' => ['privates', '.service_locator.D1WgH_c.App\\Controller\\ProductController::salades()', 'getProductControllersaladesService', true],
            'App\\Controller\\ProductController::detail' => ['privates', '.service_locator.dnfnBC4.App\\Controller\\ProductController::detail()', 'getProductControllerdetailService', true],
            'App\\Controller\\ProductController::ajaxDetail' => ['privates', '.service_locator.dnfnBC4.App\\Controller\\ProductController::ajaxDetail()', 'getProductControllerajaxDetailService', true],
            'App\\Controller\\ProductController::herbes' => ['privates', '.service_locator.D1WgH_c.App\\Controller\\ProductController::herbes()', 'getProductControllerherbesService', true],
            'App\\Controller\\RecetteController::index' => ['privates', '.service_locator.imnwLj0', 'get_ServiceLocator_ImnwLj0Service', true],
            'App\\Controller\\RecetteController::detail' => ['privates', '.service_locator.07GXJmX', 'get_ServiceLocator_07GXJmXService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ProductController:salades' => ['privates', '.service_locator.D1WgH_c.App\\Controller\\ProductController::salades()', 'getProductControllersaladesService', true],
            'App\\Controller\\ProductController:detail' => ['privates', '.service_locator.dnfnBC4.App\\Controller\\ProductController::detail()', 'getProductControllerdetailService', true],
            'App\\Controller\\ProductController:ajaxDetail' => ['privates', '.service_locator.dnfnBC4.App\\Controller\\ProductController::ajaxDetail()', 'getProductControllerajaxDetailService', true],
            'App\\Controller\\ProductController:herbes' => ['privates', '.service_locator.D1WgH_c.App\\Controller\\ProductController::herbes()', 'getProductControllerherbesService', true],
            'App\\Controller\\RecetteController:index' => ['privates', '.service_locator.imnwLj0', 'get_ServiceLocator_ImnwLj0Service', true],
            'App\\Controller\\RecetteController:detail' => ['privates', '.service_locator.07GXJmX', 'get_ServiceLocator_07GXJmXService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ProductController::salades' => '?',
            'App\\Controller\\ProductController::detail' => '?',
            'App\\Controller\\ProductController::ajaxDetail' => '?',
            'App\\Controller\\ProductController::herbes' => '?',
            'App\\Controller\\RecetteController::index' => '?',
            'App\\Controller\\RecetteController::detail' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ProductController:salades' => '?',
            'App\\Controller\\ProductController:detail' => '?',
            'App\\Controller\\ProductController:ajaxDetail' => '?',
            'App\\Controller\\ProductController:herbes' => '?',
            'App\\Controller\\RecetteController:index' => '?',
            'App\\Controller\\RecetteController:detail' => '?',
        ]);
    }
}
