<?php

namespace ContainerWENvj7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DnfnBC4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dnfnBC4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dnfnBC4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'produit' => ['privates', '.errored..service_locator.dnfnBC4.App\\Entity\\ProduitsInfo', NULL, 'Cannot autowire service ".service_locator.dnfnBC4": it needs an instance of "App\\Entity\\ProduitsInfo" but this type has been excluded in "config/services.yaml".'],
        ], [
            'produit' => 'App\\Entity\\ProduitsInfo',
        ]);
    }
}
