<?php

namespace ContainerWENvj7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_ED8a0GOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.ED8a0GO' shared service.
     *
     * @return \App\Repository\RecetteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\RecetteController::index()": the $recetteRepo argument is type-hinted with the non-existent class or interface: "App\\Repository\\RecetteRepository".');
    }
}
