<?php

namespace ContainerWENvj7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerajaxDetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dnfnBC4.App\Controller\ProductController::ajaxDetail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dnfnBC4.App\\Controller\\ProductController::ajaxDetail()'] = ($container->privates['.service_locator.dnfnBC4'] ?? $container->load('get_ServiceLocator_DnfnBC4Service'))->withContext('App\\Controller\\ProductController::ajaxDetail()', $container);
    }
}
