<?php

namespace ContainerTGDX1FG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerherbesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D1WgH_c.App\Controller\ProductController::herbes()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D1WgH_c.App\\Controller\\ProductController::herbes()'] = ($container->privates['.service_locator.D1WgH_c'] ?? $container->load('get_ServiceLocator_D1WgHCService'))->withContext('App\\Controller\\ProductController::herbes()', $container);
    }
}
