<?php

namespace ContainerTGDX1FG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitsInfoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dnfnBC4.App\Entity\ProduitsInfo' shared service.
     *
     * @return \App\Entity\ProduitsInfo
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dnfnBC4": it needs an instance of "App\\Entity\\ProduitsInfo" but this type has been excluded in "config/services.yaml".');
    }
}
