<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTGDX1FG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTGDX1FG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTGDX1FG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTGDX1FG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTGDX1FG\App_KernelDevDebugContainer([
    'container.build_hash' => 'TGDX1FG',
    'container.build_id' => 'f9484e50',
    'container.build_time' => 1743510846,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTGDX1FG');
